Repository SpiNNakerManchester/DataSpecification, pull requests merged in 2021-02, with the labels that each got.

#97 Remove Python 2.7 support
  .github/workflows/python_actions.yml
  README.md
  data_specification/data_specification_executor.py
  data_specification/data_specification_generator.py
  data_specification/exceptions.py
  data_specification/spi/abstract_executor_functions.py
  doc/doc_requirements.txt
  doc/source/conf.py
  pypi_to_import
  requirements-test.txt
  requirements.txt
  setup.py
Labels: Blocker!, bug

#98 Test 3 9
  .github/workflows/publish.yml
  .github/workflows/python_actions.yml
  doc/source/conf.py
  setup.py
Labels: enhancement, minor

#99 remove leftover six references
  .pylintrc
  README.md
  doc/doc_requirements.txt
Labels: bug, minor

#101 Stop using gitclone2.sh; use actions
  .github/workflows/publish.yml
Labels: bug, minor
